repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=40000, --enforce-all]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
        args: [--fix]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        stages: [pre-push]
        args: [--config-file=pyproject.toml]
        additional_dependencies:
          - pandas-stubs
          - types-PyYAML
          - types-aiofiles
          - types-cachetools
          - types-click
          - types-python-dateutil
          - types-python-slugify
          - types-pytz
          - types-redis
          - types-requests
          - types-seaborn
          - types-setuptools
          - types-six
          - types-tabulate
          - types-toml
          - types-tqdm
